version: "3.9"
   
services:
  db:
    image: postgres
    ports:
      - "5432:5432"
        #volumes:
        # - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=news
      - POSTGRES_USER=aman
      - POSTGRES_PASSWORD=Ihatepasswords@1234
  crawler:
    build: .
    command:  >
      bash -c
      "python manage.py makemigrations && python manage.py migrate  &&
      python manage.py runserver 0.0.0.0:3000"
    ports:
      - "3000:3000"
    depends_on:
      - db
      - memcached
  redis:
    image: redis:alpine
  celery:
    build: .
    restart: always
    command: celery -A newspaper_crawler worker --loglevel=info 
    depends_on:
        - redis
  celery-beat:
    build: .
    command: >
        bash -c
        "python manage.py makemigrations && python manage.py migrate && celery -A newspaper_crawler beat -l info --scheduler 
        django_celery_beat.schedulers:DatabaseScheduler"
    depends_on:
        - crawler
        - celery
        - redis
        - db
        - memcached
  memcached:
    image: memcached
    ports:
      - "11212:11211"
    command: memcached -vv


        

