# Generated by Django 3.2.7 on 2021-10-20 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, default='', max_length=200)),
                ('description', models.TextField()),
                ('authors', models.CharField(blank=True, default='', max_length=40)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('link', models.CharField(blank=True, default='', max_length=400)),
                ('keywords', models.CharField(blank=True, default='', max_length=400)),
                ('source_type', models.CharField(max_length=100)),
            ],
            options={
                'unique_together': {('title', 'source_type')},
            },
        ),
    ]
