# Generated by Django 3.2.6 on 2021-09-05 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('authors', models.CharField(max_length=40)),
                ('date', models.CharField(max_length=20)),
                ('link', models.CharField(max_length=400)),
                ('search_terms', models.CharField(max_length=100)),
            ],
        ),
    ]
