# Generated by Django 3.2.7 on 2021-09-16 08:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0003_rename_search_terms_article_source_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
