# Generated by Django 3.2.7 on 2021-10-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crawler', '0013_alter_article_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='keywords',
            field=models.CharField(blank=True, default='', max_length=400),
        ),
    ]
